version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: GraphQL.Server.Ui.GraphiQL
    versions:
    - 4.4.1
    - 5.0.0
    - 5.0.1
  - dependency-name: GraphQL.Server.Transports.AspNetCore
    versions:
    - 4.4.1
    - 5.0.0
    - 5.0.1
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: MongoDB.Driver
    versions:
    - 2.11.6
    - 2.12.0
    - 2.12.1
  - dependency-name: AutoMapper.Extensions.Microsoft.DependencyInjection
    versions:
    - 8.1.0
